<?php

return [
    'Results 2025' => [
        ['label' => 'All India 2025', 'route' => 'all-india-2025'],
        ['label' => 'All India Quota BDS 2025', 'route' => 'all-indida-quota-bds-2025'],
        ['label' => 'All Over India Data MBBS 2025', 'route' => 'all-over-india-data-mbbs-2025'],
        ['label' => 'Andhra Pradesh BDS Govt Quota 2025', 'route' => 'andhra-pradesh-bds-govt-quota-2025-analysis-completed'],
        ['label' => 'Andhra Pradesh BDS Management 2025', 'route' => 'andhra-pradesh-bds-management-quota-2025-analysis'],
        ['label' => 'Andhra Pradesh Govt Quota MBBS 2025', 'route' => 'andra-pradesh-govt-quota-mbbs-2025'],
        ['label' => 'Andhra Pradesh Management MBBS 2025', 'route' => 'andra-pradesh-management-quota-mbbs-2025'],
        ['label' => 'Bihar BDS 2025', 'route' => 'bihar-bds-2025-analysis'],
        ['label' => 'Bihar MBBS 2025', 'route' => 'bihar-mbbs-2025'],
        ['label' => 'Chhatisgarh BDS 2025', 'route' => 'chhatisgarh-bds-2025'],
        ['label' => 'Chhattisgarh MBBS 2025', 'route' => 'chhattisgarh-mbbs-2025'],
        ['label' => 'Deemed Universities BDS 2025', 'route' => 'deemed-universities-quota-bds-2025'],
        ['label' => 'Deemed University MBBS 2025', 'route' => 'deemed-university-mbbs-2025'],
        ['label' => 'Haryana BDS 2025', 'route' => 'haryana-bds-2025'],
        ['label' => 'Haryana MBBS 2025', 'route' => 'haryana-mbbs-2025'],
        ['label' => 'Karnataka 2025', 'route' => 'karnataka-2025'],
        ['label' => 'Karnataka BDS 2025', 'route' => 'karnataka-bds-2025'],
        ['label' => 'Karnataka MBBS 2025', 'route' => 'karnataka-mbbs-2025-analysis'],
        ['label' => 'Keral MBBS 2025', 'route' => 'keral-mbbs-2025'],
        ['label' => 'Kerala BDS 2025', 'route' => 'kerala-bds-2025'],
        ['label' => 'Madhya Pradesh BDS 2025', 'route' => 'madhya-pradesh-bds-2025'],
        ['label' => 'Madhya Pradesh MBBS 2025', 'route' => 'madhya-pradesh-mbbs-2025'],
        ['label' => 'Puducherry BDS 2025', 'route' => 'puducherry-bds-2025'],
        ['label' => 'Puducherry MBBS 2025', 'route' => 'puducherry-mbbs-2025'],
        ['label' => 'Rajasthan BDS 2025', 'route' => 'rajasthan-bds-2025-analysis'],
        ['label' => 'Rajasthan MBBS 2025', 'route' => 'rajasthan-mbbs-2025'],
        ['label' => 'Tamil Nadu BDS Govt Quota 2025', 'route' => 'tamil-nadu-bds-government-quota-2025-analysis'],
        ['label' => 'Tamil Nadu BDS Management 2025', 'route' => 'tamil-nadu-bds-management-quota-2025-analysis'],
        ['label' => 'Tamilnadu Govt MBBS 2025', 'route' => 'tamilnadu-govt-quota-mbbs-2025'],
        ['label' => 'Tamilnadu Management MBBS 2025', 'route' => 'tamilnadu-management-quota-mbbs-2025'],
        ['label' => 'Telanaga Govt MBBS 2025', 'route' => 'telanaga-govt-mbbs-2025'],
        ['label' => 'Telangana BDS Govt Quota 2025', 'route' => 'telangana-bds-govt-quota-2025-analysis'],
        ['label' => 'Telangana BDS Management 2025', 'route' => 'telangana-bds-management-quota-2025-analysis'],
        ['label' => 'Telangana Management MBBS 2025', 'route' => 'telangana-management-quota-mbbs-2025'],
        ['label' => 'Uttar Pradesh BDS 2025', 'route' => 'uttar-pradesh-bds-2025'],
        ['label' => 'Uttar Pradesh MBBS 2025', 'route' => 'uttar-pradesh-mbbs-2025'],
        ['label' => 'Uttarakhand BDS 2025', 'route' => 'uttarakhand-bds-2025'],
        ['label' => 'Uttarakhand MBBS 2025', 'route' => 'uttarakhand-mbbs-2025'],
        ['label' => 'West Bengal BDS 2025', 'route' => 'west-bengal-bds-2025'],
        ['label' => 'West Bengal MBBS 2025', 'route' => 'west-bengal-mbbs-2025'],
    ],
    'Results 2024' => [
        ['label' => 'All India Quota BDS 2024', 'route' => 'all-india-quota-bds-2024-analysis'],
        ['label' => 'All Over India MBBS 2024', 'route' => 'all-over-india-mbbs-2024'],
        ['label' => 'Andhra Pradesh BDS Govt Quota 2024', 'route' => 'andhra-pradesh-bds-govt-quota-2024-analysis'],
        ['label' => 'Andhra Pradesh BDS Management 2024', 'route' => 'andhra-pradesh-bds-management-quota-2024-analysis'],
        ['label' => 'Andhra Pradesh MBBS Govt Quota 2024', 'route' => 'andhra-pradesh-mbbs-govt-quota-2024'],
        ['label' => 'Andhra Pradesh MBBS Management 2024', 'route' => 'andhra-pradesh-mbbs-management-quota-2024-analysis'],
        ['label' => 'Deemed Universities BDS 2024', 'route' => 'deemed-universities-quota-bds-2024-analysis'],
        ['label' => 'Deemed Universities MBBS 2024', 'route' => 'deemed-universities-quota-mbbs-2024'],
        ['label' => 'Jharkhand MBBS Management 2024', 'route' => 'jharkhand-mbbs-management-quota-2024-analysis'],
        ['label' => 'Karnataka 2024', 'route' => 'karnataka-2024'],
        ['label' => 'Karnataka BDS 2024', 'route' => 'karnataka-bds-2024'],
        ['label' => 'Kerala BDS 2024', 'route' => 'kerala-bds-2024-analysis'],
        ['label' => 'My Rank MBBS Karnataka 2024', 'route' => 'my-rank-mbbs-karnataka-2024'],
        ['label' => 'My Rank MBBS Keral 2024', 'route' => 'my-rank-mbbs-keral-2024'],
        ['label' => 'My Rank MBBS Rajasthan 2024', 'route' => 'my-rank-mbbs-rajasthan-2024'],
        ['label' => 'My Rank Uttar Pradesh Dental 2024', 'route' => 'my-rank-uttar-pradesh-dental-2024'],
        ['label' => 'Rajasthan BDS 2024', 'route' => 'rajasthan-bds-2024'],
        ['label' => 'Tamil Nadu BDS Govt Quota 2024', 'route' => 'tamil-nadu-bds-government-quota-2024-analysis'],
        ['label' => 'Tamil Nadu BDS Management 2024', 'route' => 'tamil-nadu-bds-management-quota-2024-analysis'],
        ['label' => 'Tamil Nadu MBBS Govt Quota 2024', 'route' => 'tamil-nadu-mbbs-government-quota-2024'],
        ['label' => 'Tamil Nadu MBBS Management 2024', 'route' => 'tamil-nadu-mbbs-management-quota-2024-analysis'],
        ['label' => 'Telangana BDS Govt Quota 2024', 'route' => 'telangana-bds-govt-quota-2024-analysis'],
        ['label' => 'Telangana BDS Management 2024', 'route' => 'telangana-bds-management-quota-2024-analysis'],
        ['label' => 'Telangana Govt MBBS Data 2024', 'route' => 'telangana-2024-mbbs-govt-data'],
        ['label' => 'Telangana Man MBBS Data 2024', 'route' => 'telangana-2024-mbbs-mang-data'],
        ['label' => 'UP MBBS 2024', 'route' => 'up-mbbs-2024'],
    ],
    'Results 2023' => [
        ['label' => 'Karnataka 2023', 'route' => 'karnataka-2023'],
    ],
];
